POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Sarim",
  "lastName": "sarim",
  "email": "sarim@gmail.com",
  "password": "Admin@123"
}


###
POST http://localhost:8080/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNhcmltQGdtYWlsLmNvbSIsImlhdCI6MTc3NzgyNDg2MSwiZXhwIjoxNzc3ODI4NDYxLCJhdWQiOiJsb2NhbGhvc3Q6ODA4MCIsImlzcyI6ImxvY2FsaG9zdDo4MDgwIn0.kmRU__LnbwrKypxLS0K5dF-TJS_ZWXlWKWRqxocgvQU

{
  "users": [
    {
      "firstName": "Malik",
      "lastName": "jahang33ir",
      "email": "malik11233332311@gmail.com",
      "password": "Admin@123"
    },
    {
      "firstName": "Malik",
      "lastName": "jaha343ngir",
      "email": "malikkab3434eer454545@gmail.com",
      "password": "Admin@123"
    }
  ]
}

